language: ruby
rvm:
  - head
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - npm install -g svgo
  - npm install -g pngout-bin
script:
  - bundle exec middleman build
branches:
  except:
  - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  target_branch: master
  on:
    branch: src
