name: Build

on:
  pull_request:
    branches: [ src ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Node Dependencies
        run: npm ci
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Build with Middleman
        run: bundle exec middleman build
