name: merge me

on:
  workflow_run:
    types:
      - completed
    workflows:
      # List all required workflow names here.
      - 'publish website'

jobs:
  merge-me:
    runs-on: ubuntu-latest
    steps:
      - # It is often a desired behavior to merge only when a workflow execution
        # succeeds. This can be changed as needed.
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: 🩹 Merge
        uses: ridedott/merge-me-action@v2
        with:
          # This must be used as GitHub Actions token does not support pushing
          # to protected branches.
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # TODO Keep until https://github.com/ridedott/merge-me-action/issues/1581 is resolved
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPO_ACCESS }}
          PRESET: DEPENDABOT_MINOR
