name: merge me

on:
  check_suite:
    types:
      - completed

jobs:
  merge-me:
    runs-on: ubuntu-latest
    steps:
      - name: 🩹 Merge
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}